### ISSUE TITLE
render single cube

### ISSUE THREAD

**Issue by itzTheMeow** [fenomas/noa#166]
I want to render a single cube as a block preview (like classic.minecraft.net, but autogenerated)
i noticed [this](https://playground.babylonjs.com/#6XIT28#5) but it seems like it would have a huge impact on performance being done several times for each block. The render would only need to be done once, as it's a static preview, it would also only need 3 sides, like this:
![image](https://user-images.githubusercontent.com/50887230/133710286-06f6cfe5-7ea7-46bf-bb3b-e3fa99dc8b3e.png)

**Comment by fenomas** [comment]
Hi, you mean showing a phantom block where the user's cursor is pointing? That can be done by overriding the default block highlight function with similar code - just showing a solid block mesh rather than the outline the engine uses by default.

If you mean how to make the mesh itself, the straightforward way would be to call Babylon's meshbuilder "createBox" once, then just keep a reference to that mesh but change its texture depending on which block you want to show.

Does that help? Not quite sure what you're asking!

**Comment by itzTheMeow** [comment]
sorry it's a little unclear lol

i'm trying to make an cube icon for the block in a hotbar rather than just using the flat texture to indicate what block you are building with

**Comment by fenomas** [comment]
Ah I get you. If you want to render out a mesh into a png or similar, that'd be a Babylon question (i.e. orthogonal to the voxel data). In my experience the best place for Babylon info is their [forum](https://forum.babylonjs.com/), every time I've asked questions there I've gotten a lot of help.
