### ISSUE TITLE
able to add shadow to  a specific chunk but not a particular face???

### ISSUE THREAD

**Issue by levlups** [fenomas/noa#169]
in terrainMesher.js i was able to shade a particular chunk at will using the requestedID of chunk but if i use for example 
for ( var i=0;i<len0 ; i++)  if ( i<10 ) shade... it doesnt work ,it breaks down its like the chunk meshes or AOs or... wath else merges together , is their a way to keep those faces separated so we can shade certain faces and not the whole chunk.???

**Comment by levlups** [comment]
you understood right , to make realistic shadow like minecraft i need a material per face ... ??? how would I do that ....

**Comment by levlups** [comment]
heres an example of code I was using 
id is the requestedID of the chunk , but its not precise 
 function pushAOColor(colors, ix, baseCol, ao, aoVals, revAoVal,id) {
      var mult = (ao === 0) ? revAoVal : aoVals[ao - 1]
	
		
		if(parseInt(id[1])>=0){
		 
			 mult = (ao === 0) ? revAoVal : aoVals[ao - 1] 
		
		}else {
			
			mult = (ao === 0) ? revAoVal : aoVals[ao - 1]
		     mult-=0.2
		}
		
		
        colors[ix] = baseCol[0] * mult
        colors[ix + 1] = baseCol[1] * mult
        colors[ix + 2] = baseCol[2] * mult
        colors[ix + 3] = 1
    }

}

**Comment by levlups** [comment]
fenomas if your still lost , tell me Ill make you a video to explain :)

**Comment by fenomas** [comment]
Hmm, I'm still a bit lost but I guess you're tweaking the AO vertex colors based on the world position of the voxel face? 

If that's right, then the requestedID of each chunk is just an identifier, so the engine and the client know if they're talking about the same chunk or not. If you want a kind of "is this voxel above or below y=0" test, then I guess you'd want to tweak terrain meshing so that the mesher knows each chunk's world x/y/z position, and then it can track the world position of each voxel as it meshes.

Is that what you're trying to do? If so, then look at the `greedyMesher.mesh` call inside terrain mesher. If that call passed in `chunk.x, chunk.y, chunk.z` along with its other params, then the mesher would know the world position of the chunk it's meshing, and it could pass internal xyz coords down to the AO logic.
