### ISSUE TITLE
Does NOA support child meshes?

### ISSUE THREAD

**Issue by eran-sefirot** [fenomas/noa#192]
Hello!
Thanks for this great package, I am experiencing an issue where child meshes are not positioned correctly after "checkWorldOffset" completes.

I simply add a text mesh above a simple mash - which works fine, but after player entity gets close enough the child mesh (text above ball) is re-positioned incorrectly.

Thanks! :)

**Comment by eran-sefirot** [comment]
Thanks, that worked! I was trying to add the mesh as an entity
using noa.entities.add instead of using addMeshToScene.

another question - is there a way to add a skybox? /change the sky color?

Appreciate the quick response!
Thanks again for this great package !

**Comment by fenomas** [comment]
Ah good! `entities.add` is for when you want to add an "entity" - a thing that can have its own position, mesh, physics and so on.

For the sky color, you can pass the option `clearColor: [1,1,1]` when creating the engine - this is the color that is drawn to the canvas before meshes are rendered, so it's effectively the sky color. 

For a skybox, basically that should work like in any Babylon project; the only noa-specific thing is that you need to call `noa.rendering.addMeshToScene` so that the mesh will get selected for rendering.
